# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-12-24 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This is what the product will be called in the default site language.  To add non-default translations, use the Product Translation section below.', max_length=255, verbose_name='Full Name')),
                ('slug', models.SlugField(blank=True, help_text='Used for URLs, auto-generated from name if blank', max_length=255, verbose_name='Slug Name')),
                ('sku', models.CharField(blank=True, help_text='Defaults to slug if left blank', max_length=255, null=True, verbose_name='Code')),
                ('short_description', models.TextField(blank=True, default='', help_text='This should be a 1 or 2 line description in the default site language for use in product listing screens', max_length=200, verbose_name='Details of product')),
                ('description', models.TextField(blank=True, default='', help_text='This field can contain HTML and should be a few paragraphs in the default site language explaining the background of the product, and anything that would help the potential customer make their purchase.', verbose_name='Description of product')),
                ('paytmsyas', models.CharField(blank=True, default='', max_length=2000, verbose_name="paytm's thought on product")),
                ('date_added', models.DateField(blank=True, null=True, verbose_name='Date added')),
                ('active', models.BooleanField(default=False, help_text='This will determine whether or not this product will appear on the site', verbose_name='Active')),
                ('deactivate_reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='Product Deactivation Reason')),
            ],
        ),
    ]
