# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-12-24 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20181224_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__name', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='product.Brand', verbose_name='Brand'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('name',)]),
        ),
    ]
