# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-12-24 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20181224_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='freesize',
            field=models.BooleanField(default=False, verbose_name='Free Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='guide',
            field=models.TextField(blank=True, default='', help_text='This field can contain HTML and should be a few paragraphs in the default site language explaining the background of the product, and anything that would help the potential customer make their purchase.', verbose_name='Usage guide for Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='newarrivals',
            field=models.BooleanField(default=0, verbose_name='New Arrivals'),
        ),
        migrations.AddField(
            model_name='product',
            name='nonreturnable',
            field=models.BooleanField(default=False, verbose_name='NonReturnable'),
        ),
    ]
