# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-12-25 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20181224_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Prperties')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='Size')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Cost Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Selling Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default='1.0', help_text='Use this price only for this quantity or higher', max_digits=18, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Selling Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='more_colors',
            field=models.ManyToManyField(blank=True, null=True, related_name='more_colors', to='product.Color', verbose_name='More Colors'),
        ),
        migrations.AddField(
            model_name='product',
            name='more_sizes',
            field=models.ManyToManyField(blank=True, null=True, related_name='more_sizes', to='product.Size', verbose_name='More Sizes'),
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.ManyToManyField(blank=True, null=True, related_name='properties', to='product.Properties', verbose_name='Properties'),
        ),
    ]
